# Parcial 3_1

## Punto 1

1. **(15 puntos) Encontrar la solución**   

$$ x' = \begin{pmatrix}5&1\\-2&3\end{pmatrix}x $$

No puede omitir ningún paso de solución y debe describir verbalmente su procedimiento y justificar los pasos esenciales. 

2. **(10 puntos) Verifique utilizando el procedimiento de sustitución directa** 

3. (opcional) Entregar el pantallazo y conclusión de la verificación realizada en un cuaderno Colaboratory o en [Wolframe](https://www.wolframalpha.com/input/?i=x%27+%3D+%7B%7B6%2C-1%7D%2C%7B5%2C4%7D%7Dx+) y solo con estas aplicaciones. 

* No puede omitir ningún paso de solución y de cálculo algoritmicos y debe describir verbalmente   
  su procedimiento y justificar los pasos esenciales.   
* Estas descripciones y justificaciones verbales valen la mitad del punto. 

No puede omitir ningún paso de solución y de cálculo algoritmicos y debe describir verbalmente su procedimiento y justificar los pasos esenciales. 

In [1]:
import numpy as np 
A = np.array([[5,1],[-2,3]]) 
np.linalg.eig(A)

(array([4.+1.j, 4.-1.j]),
 array([[-0.40824829-0.40824829j, -0.40824829+0.40824829j],
        [ 0.81649658+0.j        ,  0.81649658-0.j        ]]))

In [2]:
from sympy import *
A = Matrix(A)
A.eigenvects() 

[(4 - I,
  1,
  [Matrix([
   [-1/2 + I/2],
   [         1]])]),
 (4 + I,
  1,
  [Matrix([
   [-1/2 - I/2],
   [         1]])])]

In [1]:
import numpy as np 
from sympy import *
t = symbols('t') 
A = Matrix([[5,1],[-2,3]])     
r_vec1, r_vec2 = A.eigenvects() 
r1, r2 = r_vec1[0]/r_vec1[1],  r_vec2[0]/r_vec2[1]
v1, v2 = A.eigenvects()[0][2][0], A.eigenvects()[1][2][0]
lambda1, mu1 = re(r1), im(r1)
lambda2, mu2 = re(r2), re(r2)

x_super1_sympy = v1*exp(r1*t)
u_sympy = re( v2*exp(lambda2*t)*(cos(mu2*t) + I*sin(mu2*t)) )
v_sympy = im( v2*exp(lambda2*t)*(cos(mu2*t) + I*sin(mu2*t)) )

display(u_sympy)
display(v_sympy)

Matrix([
[(-sin(4*re(t))*sinh(4*im(t))/2 + sin(4*re(t))*cosh(4*im(t))/2 + cos(4*re(t))*sinh(4*im(t))/2 - cos(4*re(t))*cosh(4*im(t))/2)*exp(4*re(t))*cos(4*im(t)) - (sin(4*re(t))*sinh(4*im(t))/2 - sin(4*re(t))*cosh(4*im(t))/2 + cos(4*re(t))*sinh(4*im(t))/2 - cos(4*re(t))*cosh(4*im(t))/2)*exp(4*re(t))*sin(4*im(t))],
[                                                                                                                                  -(-sin(4*re(t))*sinh(4*im(t)) + sin(4*re(t))*cosh(4*im(t)))*exp(4*re(t))*sin(4*im(t)) + (-cos(4*re(t))*sinh(4*im(t)) + cos(4*re(t))*cosh(4*im(t)))*exp(4*re(t))*cos(4*im(t))]])

Matrix([
[(-sin(4*re(t))*sinh(4*im(t))/2 + sin(4*re(t))*cosh(4*im(t))/2 + cos(4*re(t))*sinh(4*im(t))/2 - cos(4*re(t))*cosh(4*im(t))/2)*exp(4*re(t))*sin(4*im(t)) + (sin(4*re(t))*sinh(4*im(t))/2 - sin(4*re(t))*cosh(4*im(t))/2 + cos(4*re(t))*sinh(4*im(t))/2 - cos(4*re(t))*cosh(4*im(t))/2)*exp(4*re(t))*cos(4*im(t))],
[                                                                                                                                   (-sin(4*re(t))*sinh(4*im(t)) + sin(4*re(t))*cosh(4*im(t)))*exp(4*re(t))*cos(4*im(t)) + (-cos(4*re(t))*sinh(4*im(t)) + cos(4*re(t))*cosh(4*im(t)))*exp(4*re(t))*sin(4*im(t))]])

In [2]:
x_sup1 = lambdify(t, v1*exp(r1*t))

u = lambdify(t, re( v1*exp(lambda1*t)*(cos(mu1*t) + I*sin(mu1*t)) ) ) 
v = lambdify(t, im( v1*exp(lambda1*t)*(cos(mu1*t) + I*sin(mu1*t)) ) )  
c1, c2 = 1, 1
x = lambda t: c1*u(t) + c2*v(t) 

$$r_{2} = 4 + i,\ \ \ \  \xi^{(1)} = \begin{pmatrix} -1/2 -i/2 \\ 1 \end{pmatrix}$$

## Punto 2

1. **(15 puntos) Encontrar la solución**  

$$ x' = \begin{pmatrix}4&5\\-2&6\end{pmatrix}x $$

No puede omitir ningún paso de solución y debe describir verbalmente su procedimiento y justificar los pasos esenciales. 

2. **(10 puntos) Verifique** 

3. (opcional) Entregar el pantallazo y conclusión de la verificación realizada en un cuaderno Colaboratory o en [Wolframe](https://www.wolframalpha.com/input/?i=x%27+%3D+%7B%7B6%2C-1%7D%2C%7B5%2C4%7D%7Dx+) y solo con estas aplicaciones. 

* No puede omitir ningún paso de solución y de cálculo algoritmicos y debe describir verbalmente   
  su procedimiento y justificar los pasos esenciales.   
* Estas descripciones y justificaciones verbales valen la mitad del punto. 



In [3]:
import numpy as np 
A = np.array([[4,5],[-2,6]]) 
np.linalg.eig(A)

(array([5.+3.j, 5.-3.j]),
 array([[0.84515425+0.j        , 0.84515425-0.j        ],
        [0.16903085+0.50709255j, 0.16903085-0.50709255j]]))

In [4]:
from sympy import *
A = Matrix(A)
A.eigenvects() 

[(5 - 3*I,
  1,
  [Matrix([
   [1/2 + 3*I/2],
   [          1]])]),
 (5 + 3*I,
  1,
  [Matrix([
   [1/2 - 3*I/2],
   [          1]])])]

## Punto 3

1. **(15 puntos) Encontrar la solución**  

$$ x' = \begin{pmatrix}4&-5\\5&-4\end{pmatrix}x $$

No puede omitir ningún paso de solución y debe describir verbalmente su procedimiento y justificar los pasos esenciales. 

2. **(10 puntos) Verifique** 

3. (opcional) Entregar el pantallazo y conclusión de la verificación realizada en un cuaderno Colaboratory o en [Wolframe](https://www.wolframalpha.com/input/?i=x%27+%3D+%7B%7B6%2C-1%7D%2C%7B5%2C4%7D%7Dx+) y solo con estas aplicaciones. 

* No puede omitir ningún paso de solución y de cálculo algoritmicos y debe describir verbalmente   
  su procedimiento y justificar los pasos esenciales.   
* Estas descripciones y justificaciones verbales valen la mitad del punto. 

In [ ]:
import numpy as np 
A = np.array([[4,-5],[5,-4]]) 
np.linalg.eig(A)

In [ ]:
from sympy import *
A = Matrix(A)
A.eigenvects() 