# Parcial 3_3

## Punto 1

1. **(15 puntos) Resuelva el problema con valores iniciales:**

$$ x' = \begin{pmatrix} 1&1 &4 \\ 0& 2& 0 \\ 1& 1& 1 \end{pmatrix}x, \ \ x(0) = \begin{pmatrix}1 \\3 \\0 \end{pmatrix} $$

No omita ninguno de los pasos de solución o verificación describiendo y justificando verbalmente para cada caso necesario. 

2. **(10 puntos) Verifique**

No omita ninguno de los pasos de solución o verificación describiendo y justificando verbalmente para cada caso necesario. 

In [4]:
from sympy import *
A = Matrix([[1,1,4],[0,2,0],[1,1,1]]) 
r_vec1, r_vec2, r_vec3 = A.eigenvects() 
r_vec3 

(3,
 1,
 [Matrix([
  [2],
  [0],
  [1]])])

In [7]:
import numpy as np 
from sympy import *
t = symbols('t') 
A = Matrix([[1,1,4],[0,2,0],[1,1,1]])  
r1,r2,r3 = A.eigenvals().keys()  # obtendrás un diccionario 
v1,v2,v3 = A.eigenvects()[0][2][0],A.eigenvects()[1][2][0],A.eigenvects()[2][2][0] 
lambda1, mu1 = re(r1),im(r1)
lambda2, mu2 = re(r2),re(r2)
lambda3, mu3 = re(r3),im(r3) 
x_sup1 = lambdify(t,v1*(exp(lambda1*t)*cos(mu1*t) + 1*I*sin(mu1*t))) 
u = lambdify(t,re(v2*(exp(lambda2*t)*cos(mu2*t) + 1*I*sin(mu2*t)))) 
v = lambdify(t,im(v2*(exp(lambda2*t)*cos(mu2*t) + 1*I*sin(mu2*t))))  
c1,c2,c3 = 1,1,1
x = lambda t:c1*x_sup1(t) + c2*u(t) + c3*v(t) 
x(0) 

array([[ 0.5],
       [-1.5],
       [ 2. ]])

## Punto 2

Resuelva el problema con valores iniciales:

$$ \begin{pmatrix} \frac{1}{2} & 0 \\ 1 & - \frac{1}{2}  \end{pmatrix}, \ \ x(0) = \begin{pmatrix} 3 \\ 5 \end{pmatrix} $$

2. Verifique la solución encontrada por sustitución directa. 

In [1]:
from sympy import *
A = Matrix([[1/2,0],[1,-1/2]])
r_vec1, r_vec2 = A.eigenvects() 
r_vec1 

(0.500000000000000,
 1,
 [Matrix([
  [0.707106781186548],
  [0.707106781186548]])])

In [1]:
import numpy as np 
from sympy import *
t = symbols('t') 
A = Matrix([[1,1,4],[0,2,0],[1,1,1]])  
r1,r2,r3 = A.eigenvals().keys()  # obtendrás un diccionario 
v1,v2,v3 = A.eigenvects()[0][2][0],A.eigenvects()[1][2][0],A.eigenvects()[2][2][0] 
lambda1, mu1 = re(r1),im(r1)
lambda2, mu2 = re(r2),re(r2)
lambda3, mu3 = re(r3),im(r3) 
x_sup1 = lambdify(t,v1*(exp(lambda1*t)*cos(mu1*t) + 1*I*sin(mu1*t))) 
u = lambdify(t,re(v2*(exp(lambda2*t)*cos(mu2*t) + 1*I*sin(mu2*t)))) 
v = lambdify(t,im(v2*(exp(lambda2*t)*cos(mu2*t) + 1*I*sin(mu2*t))))  
c1,c2,c3 = 1,1,1
x = lambda t:c1*x_sup1(t) + c2*u(t) + c3*v(t) 
x(0) 

(array([-0.5,  0.5]),
 array([[0.        , 0.70710678],
        [1.        , 0.70710678]]))

## Punto 3

1. Determine la solución general del sistema dado:

$$ x' = \begin{pmatrix}-1 &4 &2 \\4 &-1 &-2  \\0 &0 &6  \end{pmatrix}x $$

2. Verifique la solución encontrada por sustitución directa. 

No omitir ninguno de los pasos de solución. 

Incluir las descripciones verbales y las justificaciones de los procedimientos que aplique. 


In [3]:
import numpy as np 
A = np.array([[-1,4,2],[4,-1,-2],[0,0,6]]) 
np.linalg.eig(A) 

(array([ 3., -5.,  6.]),
 array([[ 0.70710678, -0.70710678,  0.17609018],
        [ 0.70710678,  0.70710678, -0.17609018],
        [ 0.        ,  0.        ,  0.968496  ]]))

In [ ]:
from sympy import *
A = Matrix(A)
A.eigenvects()           

## Punto 4

**Presentación oral**  

$$ x' = \begin{pmatrix} & & \\ & &  \\ & &  \end{pmatrix}x, \ \ \ \ x(0) = \begin{pmatrix} \\ \\ \end{pmatrix} $$

In [ ]:
import numpy as np 
A = np.array([[],[]])
np.linalg(A)

In [ ]:
from sympy import *
A = Matrix(A) 
A.eigenvects()           